# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    images_directory_user: 'C:/xampp/htdocs/Projects/PIDEV/bellybumpImages/user/'
    images_directory_event: 'C:/xampp/htdocs/Projects/PIDEV/bellybumpImages/event/'
    #'%kernel.project_dir%/public/uploads/EventImages/'
    google_recaptcha_site_key: '%env(GOOGLE_RECAPTCHA_SITE_KEY)%'
    python_script_path: 'C:\xampp\htdocs\BellyBump\scripts\python_scripts\dbscan_script.py'
    openai.api_key: '%env(OPENAI_KEY)%'
    app.path.product_images: 'C:/xampp/htdocs/Projects/PIDEV/bellybumpImages/product/'
    images_directory_post:  'C:/xampp/htdocs/Projects/PIDEV/bellybumpImages/post/'

services:
    App\Service\RecommendationEventsService:
        arguments:
            $pythonScriptPath: '%kernel.project_dir%/public/PythonScript/EventRecommendation.py'
    # default configuration for services in *this* file
    app.logout_success_handler:
        class: App\Security\LogoutSuccessHandler
        arguments: [ '@router' ]

    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Add the DbscanService definition here
    App\Services\Dbscan:
        autowire: true

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
